name: Run Tests with Servers

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        wget -q https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install dependencies for frontend
      working-directory: ./frontend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start frontend server
      working-directory: ./frontend
      run: |
        nohup streamlit run index.py --server.port 3000 &
      env:
        PORT: 3000

    - name: Wait for frontend server to start
      run: sleep 10

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        pytest tests

    - name: Kill all Python processes
      run: |
        pkill -f python
