name: Run Tests with Servers

on:
   pull_request:
   push:
     branches:
       - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies for backend
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies for frontend
      working-directory: ./frontend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start backend server
      working-directory: ./backend
      run: |
        nohup uvicorn backend:app --reload &
      env:
        PORT: 8000

    - name: Start frontend server
      working-directory: ./frontend
      run: |
        nohup streamlit run index.py --server.port 3000 &
      env:
        PORT: 3000

    - name: Wait for servers to start
      run: sleep 10

    - name: Run backend tests
      working-directory: ./backend
      run: |
        pytest tests

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        pytest tests

    - name: Kill all Python processes
      run: |
        pkill -f python
